### PR TITLE
Add environment variable management and fix Pydantic validation error

### PR DESCRIPTION
**Pull request by downdawn**
This PR includes two separate changes:

1. Add environment variable management to the project, allowing for easier management of important configurations and distinguishing between different environments.

2. Fix a Pydantic validation error caused by None values in the links field of the Page class.

### CODE REVIEW

**Comment by wu-clan** [comment]
Hi, @downdawn 

Did you check out my comment in #7?

**Review by wu-clan — CHANGES_REQUESTED** [review]
Please check the comments #7

**Comment by wu-clan** [comment]
Hi, @downdawn 

Sorry, I just deleted the original dev branch when I PR'd, which caused this PR to be abnormal, can you resubmit the PR based on the master branch?

**Comment by downdawn** [comment]
> Hi, @downdawn 嗨， @downdawn
> 
> Sorry, I just deleted the original dev branch when I PR'd, which caused this PR to be abnormal, can you resubmit the PR based on the master branch?sorry，刚才PR的时候把原来的dev分支删掉了，导致这次PR不正常，请问能不能在master分支的基础上重新提交PR？



> Hi, @downdawn
> 
> Sorry, I just deleted the original dev branch when I PR'd, which caused this PR to be abnormal, can you resubmit the PR based on the master branch?

i didn't see the comment

Ok, I'll try to resubmit the pr to the master branch

**Pull request closed without merging**
